-- MySQL Script generated by MySQL Workbench
-- Mon May 19 21:11:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.localidade
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.localidade ;

CREATE TABLE IF NOT EXISTS mydb.localidade (
  id_municipio INT NOT NULL,
  populacao_urbana DECIMAL(10,2) NOT NULL,
  populacao_urbana_residente_agua DECIMAL(10,2) NULL,
  populacao_urbana_atendida_agua DECIMAL(10,2) NULL,
  populacao_urbana_residente_esgoto DECIMAL(10,2) NULL,
  populacao_urbana_atendida_esgoto DECIMAL(10,2) NULL,
  sigla_uf CHAR(2) NULL,
  nome_uf VARCHAR(50) NULL,
  nome_municipio VARCHAR(100) NULL,
  status_municipio VARCHAR(20) NULL,
  regiao VARCHAR(20) NULL,
  PRIMARY KEY (id_municipio));


-- -----------------------------------------------------
-- Table mydb.receitas
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.receitas ;

CREATE TABLE IF NOT EXISTS mydb.receitas (
  ano INT NOT NULL,
  id_municipio INT NOT NULL,
  receita_operacional_direta DECIMAL(12,2) NULL,
  receita_operacional_direta_agua DECIMAL(12,2) NULL,
  receita_operacional_direta_esgoto DECIMAL(12,2) NULL,
  receita_operacional_indireta DECIMAL(12,2) NULL,
  receita_operacional_direta_agua_exportada DECIMAL(12,2) NULL,
  receita_operacional DECIMAL(12,2) NULL,
  receita_operacional_direta_esgoto_importado DECIMAL(12,2) NULL,
  PRIMARY KEY (ano, id_municipio),
  INDEX id_municipio_idx (id_municipio ASC) VISIBLE,
  CONSTRAINT fk_receitas_localidade
    FOREIGN KEY (id_municipio)
    REFERENCES mydb.localidade (id_municipio)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table mydb.despesas
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.despesas ;

CREATE TABLE IF NOT EXISTS mydb.despesas (
  ano INT NOT NULL,
  id_municipio INT NOT NULL,
  despesa_pessoal DECIMAL(14,2) NULL,
  despesa_produto_quimico DECIMAL(14,2) NULL,
  despesa_energia DECIMAL(14,2) NULL,
  despesa_servico_terceiro DECIMAL(14,2) NULL,
  despesa_exploracao DECIMAL(14,2) NULL,
  despesas_juros_divida DECIMAL(14,2) NULL,
  despesa_total_servico DECIMAL(14,2) NULL,
  despesa_ativo DECIMAL(14,2) NULL,
  despesa_agua_importada DECIMAL(14,2) NULL,
  despesa_fiscal DECIMAL(14,2) NULL,
  despesa_fiscal_nao_computada DECIMAL(14,2) NULL,
  despesa_exploracao_outro DECIMAL(14,2) NULL,
  despesa_servico_outro DECIMAL(14,2) NULL,
  despesa_amortizacao_divida DECIMAL(14,2) NULL,
  despesas_juros_divida_excecao DECIMAL(14,2) NULL,
  despesa_divida_variacao DECIMAL(14,2) NULL,
  despesa_divida_total DECIMAL(14,2) NULL,
  despesa_esgoto_exportado DECIMAL(14,2) NULL,
  despesa_capitalizavel_municipio DECIMAL(14,2) NULL,
  despesa_capitalizavel_estado DECIMAL(14,2) NULL,
  despesa_capitalizavel_prestador DECIMAL(14,2) NULL,
  PRIMARY KEY (ano, id_municipio),
  INDEX id_municipio_idx (id_municipio ASC) VISIBLE,
  CONSTRAINT fk_despesas_localidade
    FOREIGN KEY (id_municipio)
    REFERENCES mydb.localidade (id_municipio)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table mydb.investimentos
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.investimentos ;

CREATE TABLE IF NOT EXISTS mydb.investimentos (
  ano INT NOT NULL,
  id_municipio INT NOT NULL,
  investimento_agua_prestador DECIMAL(14,2) NULL,
  investimento_esgoto_prestador DECIMAL(14,2) NULL,
  investimento_outro_prestador DECIMAL(14,2) NULL,
  investimento_recurso_proprio_prestador DECIMAL(14,2) NULL,
  investimento_recurso_oneroso_prestador DECIMAL(14,2) NULL,
  investimento_recurso_nao_oneroso_prestador DECIMAL(14,2) NULL,
  investimento_total_prestador DECIMAL(14,2) NULL,
  investimento_agua_municipio DECIMAL(14,2) NULL,
  investimento_esgoto_municipio DECIMAL(14,2) NULL,
  investimento_outro_municipio DECIMAL(14,2) NULL,
  investimento_recurso_proprio_municipio DECIMAL(14,2) NULL,
  investimento_recurso_oneroso_municipio DECIMAL(14,2) NULL,
  investimento_recurso_nao_oneroso_municipio DECIMAL(14,2) NULL,
  investimento_total_municipio DECIMAL(14,2) NULL,
  investimento_agua_estado DECIMAL(14,2) NULL,
  investimento_esgoto_estado DECIMAL(14,2) NULL,
  investimento_outro_estado DECIMAL(14,2) NULL,
  investimento_recurso_proprio_estado DECIMAL(14,2) NULL,
  investimento_recurso_oneroso_estado DECIMAL(14,2) NULL,
  investimento_recurso_nao_oneroso_estado DECIMAL(14,2) NULL,
  investimento_total_estado DECIMAL(14,2) NULL,
  PRIMARY KEY (ano, id_municipio),
  INDEX id_municipio_idx (id_municipio ASC) VISIBLE,
  CONSTRAINT fk_investimentos_localidade
    FOREIGN KEY (id_municipio)
    REFERENCES mydb.localidade (id_municipio)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table mydb.indices
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.indices ;

CREATE TABLE IF NOT EXISTS mydb.indices (
  ano INT NOT NULL,
  id_municipio INT NOT NULL,
  indice_agua_ligacao DECIMAL(14,2) NULL,
  indice_hidrometracao DECIMAL(14,2) NULL,
  indice_macromedicao DECIMAL(14,2) NULL,
  indice_perda_faturamento DECIMAL(14,2) NULL,
  indice_coleta_esgoto DECIMAL(14,2) NULL,
  indice_tratamento_esgoto DECIMAL(14,2) NULL,
  indice_consumo_agua DECIMAL(14,2) NULL,
  indice_fluoretacao_agua DECIMAL(14,2) NULL,
  PRIMARY KEY (ano, id_municipio),
  INDEX id_municio_idx (id_municipio ASC) VISIBLE,
  CONSTRAINT fk_indices_localidade
    FOREIGN KEY (id_municipio)
    REFERENCES mydb.localidade (id_municipio)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table mydb.infraestrutura
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.infraestrutura ;

CREATE TABLE IF NOT EXISTS mydb.infraestrutura (
  id_municipio INT NOT NULL,
  extensao_rede_agua DECIMAL(14,2) NULL,
  extensao_rede_esgoto DECIMAL(14,2) NULL,
  quantidade_sede_municipal_agua INT NULL,
  quantidade_sede_municipal_esgoto INT NULL,
  quantidade_localidade_agua INT NULL,
  quantidade_localidade_esgoto INT NULL,
  quantidade_ligacao_ativa_agua INT NULL,
  quantidade_ligacao_ativa_esgoto INT NULL,
  volume_agua_produzido DECIMAL(14,2) NULL,
  volume_esgoto_tratado DECIMAL(14,2) NULL,
  PRIMARY KEY (id_municipio),
  CONSTRAINT fk_infraestrutura_localidade
    FOREIGN KEY (id_municipio)
    REFERENCES mydb.localidade (id_municipio)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;